In [38]:
# Libary imports can go here. As always, you can import more as needed!
import pandas as pd

In [39]:
# Loads the file
file = "corrupted_titanic_data.csv"
df = pd.read_csv(file)

In [40]:
# <------------ TODO ----------------------->
# Drop all the rows with null values
df.dropna(inplace=True)
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,pclass_redundant,fare_age_combination
3,1,1,female,420.0,1,0,53.284868,S,First,woman,False,C,Southampton,yes,False,1,2.237964e+04
6,0,1,male,54.0,0,0,51.314334,S,First,man,True,E,Southampton,no,True,1,2.770974e+03
21,1,2,male,34.0,0,0,13.553364,s,Second,man,True,D,Southampton,yes,True,2,4.608144e+02
27,0,1,male,19.0,3,2,263.176986,s,First,man,True,C,Southampton,no,False,1,5.000363e+03
88,1,1,FEMALE,23.0,3,2,262.789833,C,First,woman,False,C,Southampton,yes,False,1,6.044166e+03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
916,1,2,female,150.0,0,0,5124.151314,S,Second,woman,False,E,Queenstown,yes,True,2,7.686227e+05
919,1,1,male,150.0,0,0,5123.021840,Q,First,man,True,A,Southampton,yes,True,1,7.684533e+05
922,0,1,male,150.0,0,0,5123.070311,S,First,man,True,A,Cherbourg,no,True,1,7.684605e+05
924,1,1,female,1800.0,0,2,5121.873940,S,First,woman,False,D,Southampton,yes,False,1,9.219373e+06
930,1,1,female,1800.0,0,0,5124.756454,S,First,woman,False,B,Southampton,yes,True,1,9.224562e+06

In [41]:
# <------------ TODO ----------------------->
# Drop all the feature columns that you may think are not neccessary for the models evaluation
df.drop(columns=["who", "adult_male", "alone", "alive", "pclass_redundant", "fare_age_combination", "embark_town", "class"], inplace=True)
df

     survived  pclass     sex     age  sibsp  parch         fare embarked deck
3           1       1  female   420.0      1      0    53.284868        S    C
6           0       1    male    54.0      0      0    51.314334        S    E
21          1       2    male    34.0      0      0    13.553364        s    D
27          0       1    male    19.0      3      2   263.176986        s    C
88          1       1  FEMALE    23.0      3      2   262.789833        C    C
..        ...     ...     ...     ...    ...    ...          ...      ...  ...
916         1       2  female   150.0      0      0  5124.151314        S    E
919         1       1    male   150.0      0      0  5123.021840        Q    A
922         0       1    male   150.0      0      0  5123.070311        S    A
924         1       1  female  1800.0      0      2  5121.873940        S    D
930         1       1  female  1800.0      0      0  5124.756454        S    B

[117 rows x 9 columns]

In [42]:
# <------------ TODO ----------------------->
# Clean any relevant columns here
# Make sure data is consistent and you don't have certain data entry differences like 'female' and 'FEMALE'
df.loc[df["sex"] == "female", "sex"] = 0
df.loc[df["sex"] == "FEMALE", "sex"] = 0
df.loc[df["sex"] == "male", "sex"] = 1
df.loc[df["sex"] == "MALE", "sex"] = 1

# Set embarked values of S C Q etc to all be capitalized rather than consisting of both capital and lower case
df.loc[df["embarked"] == "s", "embarked"] = "S"
df.loc[df["embarked"] == "c", "embarked"] = "C"
df.loc[df["embarked"] == "q", "embarked"] = "Q"

# Make sure the people with age limit greater than 100 have their entire row removed from the dataset
df.drop(df[df["age"] > 100].index, inplace=True)

# Reset the indices
df.reset_index(drop=True, inplace=True)
df

    survived  pclass sex   age  sibsp  parch        fare embarked deck
0          0       1   1  54.0      0      0   51.314334        S    E
1          1       2   1  34.0      0      0   13.553364        S    D
2          0       1   1  19.0      3      2  263.176986        S    C
3          1       1   0  23.0      3      2  262.789833        C    C
4          0       1   1  71.0      0      0   34.994854        S    A
..       ...     ...  ..   ...    ...    ...         ...      ...  ...
70         1       1   0  48.0      0      0   26.644362        C    D
71         1       1   0  47.0      1      1   51.065054        S    D
72         0       1   1  33.0      0      0    5.263547        S    B
73         1       1   0  19.0      0      0   27.835690        S    B
74         1       1   1  26.0      0      0   28.729591        S    C

[75 rows x 9 columns]

In [43]:
# <------------ TODO ----------------------->
# Encode all the text values to numeric ones, show all rows
df = pd.get_dummies(df, columns=["embarked", "deck"])
df

#display the info so we can verify numeric data types
df.info()

# (TIP: Double check your final dataframe at this point before moving on)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   survived    75 non-null     int64
 1   pclass      75 non-null     int64
 2   sex         75 non-null     object
 3   age         75 non-null     float64
 4   sibsp       75 non-null     int64
 5   parch       75 non-null     int64
 6   fare        75 non-null     float64
 7   embarked_C  75 non-null     bool
 8   embarked_Q  75 non-null     bool
 9   embarked_S  75 non-null     bool
 10  deck_A      75 non-null     bool
 11  deck_B      75 non-null     bool
 12  deck_C      75 non-null     bool
 13  deck_D      75 non-null     bool
 14  deck_E      75 non-null     bool
 15  deck_F      75 non-null     bool
dtypes: bool(9), float64(2), int64(4), object(1)
memory usage: 4.9+ KB

In [44]:
# <------------ TODO ----------------------->
# Create and train a classification model of your choosing
# Print the accuracy, classification report, and the confusion matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from sklearn.ensemble import RandomForestClassifier


#define x and y
X = df.drop(columns=["survived"])
y = df["survived"]

#define x and y, train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=42)

#set up scaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

#define and fit model, I chose logistic regression
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

#predict
y_pred = model.predict(X_test)

#print values
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.9333333333333333
              precision    recall  f1-score   support

           0       0.83      1.00      0.91         5
           1       1.00      0.90      0.95        10

    accuracy                           0.93        15
   macro avg       0.92      0.95      0.93        15
weighted avg       0.94      0.93      0.93        15

[[5 0]
 [1 9]]